### ISSUE TITLE
Create repo branches sheme

### ISSUE THREAD

**Issue by artmarchenko** [artmarchenko/busbot#4]
* Create ```docs``` in the project root 
* Create ```project_versioning_policy.md``` and describe it

**Comment by artmarchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Busbot-63ee673548ba310011edfe9f/issues/artmarchenko/busbot/4?planning-poker) with Zenhub @glacial-trail @vladyslavyarets

**Comment by artmarchenko** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Busbot-63ee673548ba310011edfe9f/issues/artmarchenko/busbot/4?planning-poker) with Zenhub @artmarchenko

**Comment by vladyslavyarets** [comment]
Done and merged with PR #8 (https://github.com/artmarchenko/busbot/pull/8)
